### ISSUE TITLE
Sub menu overflows out of #page, adds a horizontal scroll to the window

### ISSUE THREAD

**Issue by Nikschavan** [WordPress/twentysixteen#112]
When the last menu item has a submenu, it overflows out of the viewport, and adds a horizontal scroll o the page 

![vertical scroll](http://i.imgur.com/aA5A7h8.jpg)

**Comment by iamtakashi** [comment]
This feels like a design limitation of the menu.

Hiding child menus with `overflow: hidden` is the cure being worse than the disease. Because child menu won't be accessible (if there are more than 3 levels) and the scrollbar only appears when you hover the item anyway.

Reversing the flow to the left will be really weird and it'll require (most likely) JS and I don't think it's worth it.

This issue(?) came up with Twenty Fourteen but we'd decided to leave as it is. My vote is won't fix.

**Comment by ihorvorotnov** [comment]
> Reversing the flow to the left will be really weird and it'll require (most likely) JS and I don't think it's worth it.

Well, it's worth for large sites with mega-menus, like eCommerce etc. However, for a blog theme it's not, I totally agree.

**Comment by karmatosed** [comment]
I also vote we leave this as a restriction of the design. For now, I'm closing it as a result.
