### ISSUE TITLE
_e changed to esc_html_e for more security

### ISSUE THREAD

**Issue by maharzan** [WordPress/twentysixteen#118]
I found 2 instances of `_e` and for more security it was recommended to replace `_e` by `esc_html_e`. I have fixed those. I also found instances of `__(` such as `wp_kses( __( 'Continue reading %s'`and `sprintf( __( 'Continue reading %s'`. I am not sure if we need to convert those. If we need to I can do that as well.

**Comment by fklein-lu** [comment]
In case of the "Continue reading %s” string in for example `content.php`, you are correct in saying that this string could be escaped instead of using `wp_kses()` to secure the translation.

I think this particular code is a left over from _s,:

```
the_content( sprintf(
                /* translators: %s: Name of current post. */
                wp_kses( __( 'Continue reading %s <span class="meta-nav">&rarr;</span>', '_s' ), array( 'span' => array( 'class' => array() ) ) ),
                the_title( '<span class="screen-reader-text">"', '"</span>', false )
            ) );
```

In _s, you could not escaped that string, because it contains HTML, but in Twenty Sixteen it doesn't, so you can go ahead and submit a PR for this.

Please make sure that the PR is made against an up to date repository, and that all changes are combined in a single PR.

**Comment by maharzan** [comment]
have committed.. Thanks. :)

**Comment by karmatosed** [comment]
@maharzan where did you commit? Not seeing it linked to this.

**Comment by karmatosed** [comment]
I'm assuming this is the updated one: https://github.com/WordPress/twentysixteen/pull/119? It's still out of sync so really we need that resolved.

**Comment by maharzan** [comment]
Thanks. I did an update here. I hope that won't go out of sync. :)

https://github.com/WordPress/twentysixteen/pull/119
