### ISSUE TITLE
Post Formats - Aside vs Status

### ISSUE THREAD

**Issue by dshanske** [WordPress/twentysixteen#126]
What about distinguishing aside from status by displaying the post author avatar on status?

Wanted to discuss styling for these two, as status is used less often in my experience than aside. But from the original description of status, I think it would display in a manner similar to, for example, Twitter.

**Comment by iamtakashi** [comment]
The difference between aside post and status post is title because status doesn't need it at all. I'm not sold on the idea of showing author avatar if it's a single author blog. I don't see it as a big gain to make the theme complicated. Twenty Sixteen doesn't highlight post formats at all and I'm not up for adding special styling to different formats.

**Comment by karmatosed** [comment]
I also don't think this is something worth pursuing. Status doesn't have to display like Twitter, that's up to the theme. For now, as @iamtakashi isn't keen either lets close this. I am keen we keep design decisions to him.
