### ISSUE TITLE
The link color in Green Color Options isn't so readable

### ISSUE THREAD

**Issue by maharzan** [WordPress/twentysixteen#133]
I think a darker like #297760 could be better. Right now, there is less contrast and its very hard to read the links/sidebars.

**Comment by karmatosed** [comment]
I think this is a design decision, so tagging for review.

**Comment by maharzan** [comment]
Just so when we are here, the gray color for some fonts are also pretty hard to read.. maybe I m just getting old. :)

**Comment by iamtakashi** [comment]
Some colours in a few colour schemes are low contrast but that's intentional design decision when we have the high contrast default colour scheme. We aren't forcing theses colours as people can change them very easily.

People can have any opinion on any colour but I don't want to change any colour.
