### ISSUE TITLE
Single posts show full content as well as post excerpt

### ISSUE THREAD

**Issue by Nikschavan** [WordPress/twentysixteen#141]
![single posts show excerpts](http://i.imgur.com/BKZ4tUC.jpg)

The same is the result on `blog page`.

This is when excerpt manually added to the post

When looking into code, in `content-single.php` the excerpt is explicit printed on the screen. Is this intentional? 

~ Nik

**Comment by iamtakashi** [comment]
Yes. It's meant to be used as an intro. We will clarify this feature in readme.txt.

**Comment by brentlogan** [comment]
Unusual uses of standard features makes it difficult to transition a long term blog to twenty sixteen. Looks like I'll be going through all my posts and deleting all my handcrafted excerpts. :-(

**Comment by doughamlin** [comment]
Agreed. It seems like this could cause a great barrier to entry (and exit) in using Twenty Sixteen. I think a post meta field makes more sense for this use (not that I'm advocating that; I understand what a can of worms that would open).

**Comment by philiparthurmoore** [comment]
I could see this being a nightmare for theme switchers and users with custom excerpts on hundreds of posts. As a design decision I think it's **beautiful** but if the support questions from [Subtitles](https://wordpress.org/plugins/subtitles/) have been any indication to me it's that there are people who really do take advantage of those custom excerpts on a ton of posts in weird ways because built-in subtitles functionality doesn't exist in WordPress (which is why I built the plugin).

/me hopes and prays that doesn't come across as some sort of plugin pitch.

Custom excerpts have become a roundabout answer to many different problems. I'm curious to see what switch will be like for a lot of users with this approach.

**Comment by philiparthurmoore** [comment]
^ If it wasn't clear from my comment above, I think the actual design approach there with the sub-text under the title is lovely. Always wished there were an easy way to do that with WordPress.

**Comment by ihorvorotnov** [comment]
@philiparthurmoore if someone uses excerpts for kind of subtitles (or a 1-2-3 sentence "long title" / description) isn't it going to be perfectly fine with current design decision? Like, a title, followed by visually enhanced excerpt (be it a subtitle or longer description), followed by actual content. Am I missing smth here?

**Comment by philiparthurmoore** [comment]
Yes, I'm not actually advocating taking that out at all. I love it. But don't custom excerpts support any sort of HTML that's also allowed in a post? (That may be edge case territory.)

As I said, I'm mostly interested in actual user feedback. I love what Takashi has done there with the placement of it.

**Comment by iamtakashi** [comment]
Thanks for feedback, guys.

Yes, it maybe unusual but this is something I'd like to try because we've never done that in past default themes.

People might have used the excerpt field in a lot of different ways in past, and there is no way to know all the cases. But if we think about what the excerpt field is really meant for, it is a place to add a quick summary of a post, and I think it works really well for the purpose the theme intends with the intro. And the best thing is that we're using the feature Core already provides us.

In my opinion, it makes sense from terminology point of view, and it's the simplest method that we don't need hundreds of additional code in the theme.

**Comment by philiparthurmoore** [comment]
Couldn't agree more. Doesn't hurt to try new things. :) Looks fantastic.

**Comment by ihorvorotnov** [comment]
Agree.

> People might have used the excerpt field in a lot of different ways in past, and there is no way to know all the cases

As a theme developer (currently building a free **blog** theme for WP.org with a Pro version) I would be happy to know more about these kind of usage, even edge cases.

For example, here's how I did it on a news site for one of my clients (and it will work perfectly with twentysixteen):

![2015-09-09_19-02-30](https://cloud.githubusercontent.com/assets/1066083/9769391/9e8a8112-5732-11e5-8a93-0c5236bc2f35.png)
