### ISSUE TITLE
Static front page displaying "Content Bottom"

### ISSUE THREAD

**Issue by ehti** [WordPress/twentysixteen#224]
By default, the Content Bottom sidebars are only set to show on indivual posts or pages. They don't appear on the front page either, but when it's set to a static front page, they do show up. Pull request incoming for this, please review.

Also, content bottom sidebar was recently allowed to be displayed on 404 page, so why not on category and archive pages as well? If you approve it, can open a separate issue and send PR.

**Comment by iamtakashi** [comment]
As the name suggests, the widget areas are meant to only appear the bottom of single content. The idea is simple — suggesting users where to go after they consumed the single content. Therefore, it makes sense to appear if a static page is set to be the front page. They are different from so called "footer widgets" and are never meant to appear on a page where there is a list of posts — posts page and archive pages.

We've decided to add it on 404 page because it can be useful on the page, and it's not derailing radically from the initial idea — widget ares for a single page.

I appreciate your suggestion but hiding it on the front page doesn't make sense, and adding it on archive pages or posts page is derailing from the initial concept.

**Comment by ehti** [comment]
I get it now, thanks. My thought behind it was that often a static front page is used to give a blog more of a "website" look, came across this request quite a few times on support forums.
