### ISSUE TITLE
Accessibility: Add More Advanced Keyboard Navigation to Dropdown Navigation

### ISSUE THREAD

**Issue by davidakennedy** [WordPress/twentysixteen#256]
A suggestion from #253. This would be a nice enhancement, and a step further than what has been done in past default themes.

Currently, keyboard users can get to all the links in dropdown menus, but it's harder to jump around from link to link, sub-item to sub-item, especially with larger menus. The current way is solid, but this would make it better. We have a pattern for this in the Accessible Theme Patterns that might be a great starting point: https://github.com/wpaccessibility/a11ythemepatterns/tree/master/menu-keyboard-arrow-nav Contributed by @tellthemachines.

From the original issue:
- Users should be able to select ‘ESC’ to close a drop-down menu, and then when tabbing or arrowing again they are taken to the next main menu item.
- Screen reader users have to go through all submenu items in order to get to another menu item
- Currently, if you want to navigate to “Page B,” you have to tab through the entire main nav, sub items included.

**Comment by tywayne** [comment]
I worked on this a little bit today, using the linked pattern above as a starting point, and have a solution locally that allows using arrow keys to move around, as well as 'ESC' to get out of a sub-menu.
[Example showing this in action shown here.](https://cloudup.com/c6vN5wEl2bA)

This covers the first and third item in that list, but before I submit a PR, I wanted to get your input on the second item.

> Screen reader users have to go through all submenu items in order to get to another menu item

Not exactly sure what would need to be done to alleviate this issue, any thoughts?

**Comment by afercia** [comment]
This will work for keyboard users who don't use a screen reader but won't work for screen reader users unless we use "role=application" on the whole menu. And "role=application" should be used only for real ARIA widgets, I wouldn't recommend to use it here,
The reason why it won't work it's because screen readers intercept key presses and there won't be a "keydown" event when pressing the arrow keys. It's the same reason why the media grid in the WordPress admin doesn't work with screen readers :) There are more places in the admin where this happens, for example the Toolbar menu.
So, screen readers intercept most of the key presses (except for example Tab, Enter, and a few others). Browsers will not be aware that a key press happened. No key press,  no keyboard event.

> Screen reader users have to go through all submenu items in order to get to another menu item

Screen reader users have shortcuts to jump through list items.

**Comment by joedolson** [comment]
I think we need to be clear on the goal for this - since screen readers have their own custom navigation methods, this should be intended to provide better accessibility for keyboard-dependent users. It doesn't matter if these features don't work in a screen reader, as long as they don't interfere with the behavior of the screen reader. 

For point 2 what's more accurate is that _keyboard users_ have to go through all items of a submenu to move on. The solution for that would be the ability to use the left and right key to move to the next main menu item from within the current submenu. E.g., when in a sub menu, up and down navigate you within the menu; left moves to the previous main menu item (if there is one), right moves to the next main menu item (if there is one.)

**Comment by karmatosed** [comment]
As discussed today was the cut off point for PR. With that in mind, this is going to be closed.
