### ISSUE TITLE
Disqus integration

### ISSUE THREAD

**Issue by brentlogan** [WordPress/twentysixteen#329]
I just started experimenting with Disqus and Twenty Sixteen. I'm curious whether we want to simplify integrating Disqus into Twenty Sixteen. I think it would be a good idea. 

For many screen widths, Disqus looks fine, as is matches the width of #main. When the screen width gets narrower, Disqus no longer looks good. Below a screen width of 710px, Disqus has no margins or padding and runs to the edge of the screen.

I would propose something like the following:

```
#disqus_thread {
    margin: 0 7.6923% 3.5em;
}

@media screen and (min-width: 56.875em) {
    #disqus_thread {
        margin: inherit;
    }
}
```

Some might argue that a better breakpoint would be 710px. It's not a hill for me to die on. :-)

I've made the change on my blog so you can see what it looks like (not that I really get comments). You can see the Disqus form here: http://brentlogan.com/2015/10/seven/

Drag your window width to see the changes.

**Comment by karmatosed** [comment]
There's a long list of things that everyone will think should and shouldn't be supported in Twenty Sixteen. That's great, because in the world of WordPress we all have our own methods, choices and variations. That's exactly why child themes exist too. It would not be a good way to go, to have everyone's options in a default theme. As a result, for now I'd suggest integrating like this wouldn't be something shouldn't be included.

I would also point you to looking at ems and % for break points not px. Just as a note when you consider break points.

**Comment by iamtakashi** [comment]
A core theme should never carry any third-party plugin specific style.

**Comment by brentlogan** [comment]
Thanks everyone for the feedback. I only bring it up because I've seen many Twenty Fifteen blogs using Disqus that have no customization applied. It's not pretty and, in my mind, reflects on the theme as well.

I guess I'm remembering the practice of many years ago where theme authors would included CSS for third party plugins for breadcrumbs and navigation. If that's old school, no problem. :-)

And @karmatosed, my proposed CSS used ems, but I intended to say that some might prefer a narrower breakpoint, not using px. 710px would correspond to 44.375em. In retrospect, I realize my comment was ambiguous and unclear.

**Comment by grappler** [comment]
It is still good to add support for plugins in a theme but there are so many plugins that it is impossible to support all plugins. 

You can always create a child theme or offer the CSS snippet on your website that others can use.

**Comment by brentlogan** [comment]
@grappler, good idea! Done. :-)
