### ISSUE TITLE
Customizer Option for Sidebar positioning

### ISSUE THREAD

**Issue by mathetos** [WordPress/twentysixteen#36]
I like that the sidebar is on the right-hand side by default. It is an "aside" and reading starts to the left, so it makes sense. But reading doesn't start to the left for everyone. Should there be an option to have the sidebar on the left specifically for RTL readers? Of course it has benefits for LTR readers as well if they just have a preference.

**Comment by karmatosed** [comment]
I'm firmly in the less options camp and as such would vote to not do this. Rtl in itself should reverse without an option.

**Comment by mathetos** [comment]
Reversing without an option sounds great too. Happy to work on that if you'd like that supported.

**Comment by celloexpressions** [comment]
RTL would reverse automatically. However, it would be good to have a no-sidebar option similar to the one in twentyeleven, and that could also include a left-sidebar choice. This can be easily implemented with postMessage previewing in the Customizer, by toggling a body class, to optimize the UX. While we need to be careful with how many options are available, a few strong options that make significant changes with minimal user effort is better than creating something that users cannot tweak at all without knowing CSS.

**Comment by mathetos** [comment]
The "No Sidebar" option I think should be a page template (but that doesn't address posts/attachments at all). But having a global "Left/Right" Sidebar option does make sense to me. As far as "WHERE" that can happen in the Customizer, I'd vote on changing the "Site Identity" section to be "General Options" and keep Site Identity in there and then the Sidebar global.

Overall, still feels like an important conversation to have.

**Comment by karmatosed** [comment]
We have a few variations that allow a variety of combinations:
- rtl moves the sidebar
- no widgets has it with single column

As a result, the extra option is really a design decision. We're not making a framework or theme to suit everyone, that's why child themes are so popular with themes. You get to in a child theme do your own variations. Options also add hurdles for users, which we want to avoid.

As a result of all of the above, this won't be implemented in Twenty Sixteen.
