### ISSUE TITLE
Third level dropdown menu hidden off screen if parent is pushed to leftmost side.

### ISSUE THREAD

**Issue by josephfusco** [WordPress/twentysixteen#394]
It doesn't seem like we are detect viewport edges for dropdowns and I believe we really should. Correct me if I'm wrong but this just doesn't seem like that extreme of an edge case.

If a third level dropdown menu is in the 1st menu position with approximately 7 - 9 shorter top level menu titles at screen sizes approaching 910px, it will be hidden. Since depth is allowed greater than 2, I truly believe we should have something in place handle a flip from a left side position to a right.

<img width="885" alt="screen shot 2015-12-07 at 7 30 59 pm" src="https://cloud.githubusercontent.com/assets/6676674/11644705/5af6f824-9d1c-11e5-91ef-5b5338246a48.png">

**Comment by iamtakashi** [comment]
The design decision was made in #321.

I wouldn't call this is an extreme edge case but isn't likely scenario either. Also users can add child menus where they work best in this theme.

I wouldn't say this is perfect but, in my opinion, this is one of those design limitations of the fly-out / dropdown menu pattern. We always can have a case where it breaks unless we use heavily JS to catch all the possibilities.

As you can see in #321, we've settled with an approach that aims to most likely scenarios because there is always a situation the menu breaks.

**Comment by josephfusco** [comment]
Understandable. Thanks for the quick reply. :smile:
