### ISSUE TITLE
Inconsistent h2.entry-title sizes

### ISSUE THREAD

**Issue by shelleyvadams** [WordPress/twentysixteen#442]
The title (`h2.entry-title`) in standard posts (`article.format-standard`) is much larger than in the other post types I've used -- image (`article.format-image`), link (`article.format-link`), and video (`article.format-video`).

In a list of posts (e.g., category archive) this looks very odd. The difference is more striking on larger screens:
- 28px vs. 19px, base;
- 33px vs. 19px, width ≥ 710px `screen and (min-width: 44.375em)`
- 40px vs. 23px, width ≥ 985px `screen and (min-width: 61.5625em)`

**Comment by iamtakashi** [comment]
The reason why is to deemphasise the post title in those formats because less important for those format. Using standard format instead should do if the title is important and the treatment is not desirable.

Anyway, this was a design decision made a long time ago and we're not going to able to change this from now since this would affect hundreds of thousands sites.
