### ISSUE TITLE
Featured image showing at thumbnail size after changing to 2016 theme

### ISSUE THREAD

**Issue by chrisaldrich** [WordPress/twentysixteen#453]
I recently switched from an older generic theme to twenty sixteen and am having problems with featured images. Even though the originals are reasonably large (>1000px typically), they show up instead as if they're thumbnail sized.

Removing the featured image and then attempting to add it back doesn't seem to resolve the problem either -- I still get the small thumbnail-sized photo. Similarly, changing it to a new/different photo seems to work fine and it's featured at the correct size, but then changing it in the interface back to the original photo has it ouput again as a thumbnail?!

I've gone back and re-added photos manually which definitely fixes issue, but would prefer not to have to do this for hundreds of posts. Has anyone else moving to this theme had this issue?   

As an example, take a peek at: http://boffosocko.com/2015/05/09/schools-of-thought-in-the-hard-and-soft-sciences/

The output code for the incorrect featured image appears to be: 
`<div class="post-thumbnail">`
`<img width="120" height="80" src="http://i1.wp.com/boffosocko.com/wp-content/uploads/2015/05/20150509090325.png?fit=120%2C80" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="Firmness of Science vs. # of Schools of Thought" sizes="(max-width: 709px) 85vw, (max-width: 909px) 67vw, (max-width: 984px) 60vw, (max-width: 1362px) 62vw, 840px">    </div>`

Why would this happen with old (prior to the theme change) featured photos but not newly uploaded photos?

**Comment by iamtakashi** [comment]
Just switching theme won't generate new sizes of thumbnails specified in the new theme. This isn't theme specific thing. You will need to regenerate thumbnail and use this handy plugin. https://wordpress.org/plugins/regenerate-thumbnails/

Since this repo is more for development, reporting bugs, and suggesting improvements, it is best to post a question like this here: https://wordpress.org/support/forum/themes-and-templates
