### ISSUE TITLE
List item text aligns with paragraph

### ISSUE THREAD

**Issue by ericandrewlewis** [WordPress/twentysixteen#461]
I'm sure this was an intentional design decision, but I'm curious about the decision-making on out-denting the list item bullet and aligning the list item text with paragraphs.

**Comment by ericandrewlewis** [comment]
Sorry I meant twentyfifteen :)

**Comment by ericandrewlewis** [comment]
Actually, twentysixteen does it too so this is just as good a place to answer this question.

**Comment by iamtakashi** [comment]
As you imagined, it is indeed intentional. They are called hanging punctuation. If you google it you'll see what they are about and its benefits.

As design is mostly subjective, there are mixed opinions about it, but I, as the designer of both themes, made the decision to apply the practice as I personally think it is better to keep the flow of text.

I hope this clarifies.
