### ISSUE TITLE
Add print style in the main stylesheet

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/twentysixteen#7]
Like other default themes, let's add print style at the bottom of the main stylesheet.

**Comment by ihorvorotnov** [comment]
The fact it's done this way in other default themes does not mean it's the right way to do. Only a tiny fraction of users / page views will end up in printing the page. Why load that extra kilobytes? There's a link's `media="print"` attribute to serve print-specific stylesheet only when user needs it.

**Comment by karmatosed** [comment]
This came up in the weekly meeting, @iamtakashi is going to research and find out why this was done in that way in previous themes.

**Comment by ihorvorotnov** [comment]
The Codex [says](https://codex.wordpress.org/Styling_for_Print#Creating_Print_Styles):

> Styles associated with printing can be set in two different ways. If you want very simple changes to the site for easy printing, you can use the first method and add them directly to the style sheet. If you want to control the end result of your site when printed, it is best to keep these in their own print.css style sheet.

I've Googled for some best practices in the real world, however, there's no consensus over this topic. Both options are valid, and the Codex recommendation sounds pretty logical to me. If it's just a few lines of simple changes - put it in the main stylesheet. Otherwise go with a separate file.

**Comment by iamtakashi** [comment]
Thanks @ihorvorotnov for the research.
