### ISSUE TITLE
Border on Menus with Submenus enhancement

### ISSUE THREAD

**Issue by maharzan** [WordPress/twentysixteen#99]
I thought the boxy border didn't go well with the menu items with submenus (on the mobile nav). It looks odd on the overall neat design.

**Comment by iamtakashi** [comment]
@maharzan, thanks for your suggestion but I think it's better to leave as it is.

The reason for the side borders is to help to communicate with users that the arrow and the rest of menu item do different things. The arrow displays child menu and the rest takes you to the page. Without the borders, it could look the entire menu item shows child menu on tap, similar to how the desktop menu works.

**With border:**
![with-border](https://cloud.githubusercontent.com/assets/908665/9655002/4728d93e-5226-11e5-8ee4-749ddd1f8893.jpg)

**Without border:**
![without-border](https://cloud.githubusercontent.com/assets/908665/9655004/50dfcef6-5226-11e5-8bd1-688f65864a8d.jpg)

**Desktop menu  mouseover _the whole menu item_:**
![screen shot 2015-09-03 at 10 21 07](https://cloud.githubusercontent.com/assets/908665/9654927/d37c6898-5225-11e5-83d4-b9de75901558.png)

**Comment by karpstrucking** [comment]
couple alternatives for consideration:

![image](https://cloud.githubusercontent.com/assets/999261/9657786/12227588-5212-11e5-8534-e0c76a56227e.png)

![image](https://cloud.githubusercontent.com/assets/999261/9657775/0112826a-5212-11e5-85e7-2f12973c7b51.png)

**Comment by MonikaTS** [comment]
The second thing I've done in my test child theme is to alter this arrows to "+" and " -".
I have to realize that most of my customers do not click arrows, because they do not know whats behind or fear them or ...?
 But they are willing to click "+" for open something and "-" to close something.

**Comment by iamtakashi** [comment]
> But they are willing to click "+" for open something and "-" to close something.

The "plus" and "minus" icons are certainly good alternatives but I have not seen a test result that shows these icons actually perform a lot better than a chevron or a triangle.

This is <a href="https://viget.com/inspire/testing-accordion-menu-designs-iconography">the closest study</a> I know but it concludes there is no big difference between icon choices.

**Comment by MonikaTS** [comment]
maybe :-) but I had to alter  button class="dropdown-toggle"  expand child menu.... because of Google guidelines "Mobile usability" and something more (meta results ie.) so I alter the icons too.

**Comment by iamtakashi** [comment]
> I had to alter button class="dropdown-toggle" expand child menu.... because of Google guidelines "Mobile usability" and something more (meta results ie.)

Interesting. If you have suggestions and even better with support material or data, please raise an issue and add a PR.

**Comment by MonikaTS** [comment]
oh my Goodness :-) (((( thats why I hate github)))
 I will try, because of you and your theme. Ok I hate the screenshot I will not see a "notice of sometones death" in my WP :-) but I fall in love with your content organisation. You are playing with vertical lines in a beautiful way.  
I dont't know how to "raise an issue or add a PR (=?) ...
But not this day, deadline is waiting , but I will try :-)

**Comment by iamtakashi** [comment]
OK, a PR is not necessary, if you aren't comfortable making. It'd be helpful if you can just raise an issue with your idea to solve the issue. Also if you have supporting material (like the guideline from Google you mentioned), please add a link to it please. But no rush :)

Thanks for the kind words.

**Comment by maharzan** [comment]
Yea, you might be right on that the box distinguishes its action but the design... I am not sure! It just looks totally off with the rest of the menu items..

**Comment by iamtakashi** [comment]
@karpstrucking, thanks for your suggestions. Both look better than without borders and here is what I think about them.

**Top:** I like the subtle border but I'm not sure if the button is going to be visually loud enough as a button when the parent menu item spans two lines.

**Bottom:** I have considered this option before but I've dropped it because it introduces another design pattern in the theme — light grey button which is not used in anywhere else. I think it's better to limit design pattern minimum specially the theme has custom color option.

**Comment by karmatosed** [comment]
Do we have a PR brewing for this?

**Comment by iamtakashi** [comment]
I'm considering to implement the first idea from @karpstrucking. But I'm not sure yet.

**Comment by karmatosed** [comment]
Awesome, I'll leave it in your capable hands then :)

**Comment by maharzan** [comment]
@iamtakashi My vote to the first idea as well.
